config_proj_secao_f_10_2019 <- 
  list(admitidos_CAGED = c("1", "2"), 
       cor_CAGED = c("1", "2", "4", "6", "8", "9"), 
       horas_CAGED = 44, 
       ind_trab_parcial = c("1", "0"), 
       ind_trab_intermitente = c("1", "0"), 
       uf_cod_CAGED = c("35", "33", "32", "31", "41", 
                        "43", "42", "13", "14", "16", "15", "17", "11", "12", "21", "22", 
                        "23", "24", "26", "25", "28", "27", "29", "51", "50", "52", "53"), 
       porte_empresa_CAGED = c("5", "6", "7", "8", "9"), 
       escolaridade_CAGED = c("1", 
                              "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"), 
       sexo_CAGED = c("1", "2"), 
       n_ref = 12, 
       salario_minimo_atual = 998, 
       salario_minimo_anterior = 954, 
       salario_minimo_anterior2 = NA, 
       salario_minimo_anterior3 = NA, 
       perc_auxilio_acidente = 0.0895, 
       tipo_movimentacao = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "25",  "43", "90"), 
       valor_exame = 93.15, 
       periodicidade = 24, 
       jornada_diaria_trabalho = 7.33333333333333, 
       horas_treinamento = 0, 
       meses_ano = NA, 
       dias_ano = NA, 
       dias_semana = NA, 
       domingos_ano = NA, 
       dias_ferias = NA, 
       taxa_deposito_fgts = 0.5, 
       dias_licenca_maternidade = NA, 
       dias_licenca_paternidade = NA, 
       dias_ausencia_justificada = NA, 
       dias_aviso_previo = NA, 
       reducao_jornada_diaria_trabalho = NA, 
       proporcionalidade = FALSE, 
       fator_infraestrutura = "1", 
       horas_globais_trabalhaveis = "1", 
       desvio_padrao = "2", 
       desvio_padrao_n = "5",
       criterio_amostras = "1", 
       criterio_amostras_n = 0, 
       encargo_ferramentas = "2", 
       encargo_epis = "2", 
       corte_piso = "2", 
       n_media_movel = "1")


# par_gerais # Gerais
# par_calc # Padrão
